//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekBooks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReview
    {
        public int ReviewID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReviewRating { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
