//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekBooks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingAddress
    {
        public int ShippingAddressID { get; set; }
        public string Street { get; set; }
        public Nullable<int> Apt { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public Nullable<int> FK_ShippingUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
