//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeekBooks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shoppingcart_Book
    {
        public int ID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> PriceEach { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Shoppingcart Shoppingcart { get; set; }
    }
}
